import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ariel Developer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-[30em]">
              <Image
                src={profilePic}
                alt="Ariel Videla"
                className="w-full h-auto"
                priority
                sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw, 33vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Convertir la visión en realidad con código y diseño."
                className="!text-5xl !text-left"
              />
              <p className="my-4 text-base font-medium">
                Como desarrollador full-stack, me dedico a convertir ideas en
                aplicaciones web innovadoras. Explore mis últimos proyectos, que
                muestran mi experiencia en Frontend, Backend, en el desarrollo
                web.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/Ariel.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"
                  download={true}
                >
                  CV <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:ariel_videla@hotmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light"
                >
                  Contacto
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image src={lightBulb} alt="ariel videla" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
